name: GitHub Release Pipeline

on:
  release:
    types: [released]

jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.var_step.outputs.version}}
      output2: ${{steps.date_step.outputs.docdate}}
    steps:
      - name: Checkout interface
        uses: actions/checkout@v3
        with:
          path: dist/open-simulation-interface
      - name: Set version
        id: var_step
        working-directory: dist/open-simulation-interface
        run: version=$(git describe --tags --always |  sed 's/^v//') >> $GITHUB_OUTPUT 
      - name: Set date
        id: date_step
        run: echo "docdate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - run: echo ${{steps.var_step.outputs.version}} ${{steps.date_step.outputs.docdate}}

  antora:
    name: Generate Antora content
    runs-on: ubuntu-22.04
    steps:          
      - name: Checkout Antora generator
        uses: actions/checkout@v3
        with:
          repository: OpenSimulationInterface/osi-antora-generator
          path: antora
          submodules: true

      - name: Manipulate site.yml
        working-directory: antora
        run: |
          sed -i -E 's/branches: (.*) \# (open-.*|osi-.*)//g' site.yml


      - name: Create run instructions
        run: |
          echo "#!/bin/bash
          
          cd antora
          exec antora --stacktrace --fetch --clean site.yml" > antora.sh
          cat antora.sh

      - name: Run Antora
        uses: docker://ghcr.io/asam-ev/project-guide-docker:4
        with:
          entrypoint: sh
          args: antora.sh
          
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with: 
          name: antora
          path: antora/site
  
  deliverables:
    name: Create deliverables package
    runs-on: ubuntu-latest
    needs: [setup,antora]
    steps:
      - name: Checkout interface
        uses: actions/checkout@v3
        with:
          path: dist/open-simulation-interface

      - name: Checkout sensor model packaging
        uses: actions/checkout@v3
        with:
          repository: OpenSimulationInterface/osi-sensor-model-packaging
          path: dist/osi-sensor-model-packaging
          
      - name: Retrieve Antora artifact
        uses: actions/download-artifact@v3
        with:
          name: antora

      - run: echo ${{needs.setup.outputs.output1}}
      - run: version=${{needs.setup.outputs.output1}}
      - run: echo ${{needs.setup.outputs.output2}}
      - run: docdate=${{needs.setup.outputs.output2}}
      
      - name: Create README
        working-directory: dist
        run: |
          echo "/**********************************************************************************
          ***  ASAM OSI       		                                                ***
          ***  Version : $version       	                                        ***
          ***  Date:  $docdate                                                       ***
          **********************************************************************************/

          The deliverables of ASAM OSI $VERSION include:

          - ASAM_OSI_Standard_$version
          - open_simulation_interface_$version
          - osi-sensor-model-packaging_$version" > "README.txt"
          cat README.txt

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with: 
          filename: ASAM_OSI_$version.zip
          path: dist
          
      - name: Create deliverables package
        uses: actions/upload-artifact@v3
        with:
          name: deliverables
          path: ASAM_OSI_$version.zip

  publish:
    name: Add deliverables to release
    runs-on: ubuntu-latest
    needs: [deliverables, setup]
    steps:
      - name: Retrieve previous artifacts
        uses: actions/download-artifact@v3
        with:
          name: deliverables
      
      - run: version=${{needs.setup.outputs.version}}
      
      - name: Add deliverables to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ASAM_OSI_$version.zip
          tag: ${{ github.ref }}
