name: GitHub Release Pipeline

on:
  release:
    types: [released]

jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout interface
        uses: actions/checkout@v3
        with:
          path: dist/open-simulation-interface
      - name: Set vars
        working-directory: dist/open-simulation-interface
        run: VERSION=$(git describe --tags --always |  sed 's/^v//') && echo $VERSION
    outputs:
      VERSION: $VERSION

  antora:
    name: Generate Antora content
    runs-on: ubuntu-22.04
    steps:          
      - name: Checkout Antora generator
        uses: actions/checkout@v3
        with:
          repository: OpenSimulationInterface/osi-antora-generator
          path: antora

      - name: Manipulate site.yml
        working-directory: antora
        run: |
          sed -i -E 's/branches: (.*) \# (open-.*|osi-.*)//g' site.yml

      - name: Create run instructions
        run: echo "#!/bin/bash\n\ncd antora\nexec antora --stacktrace --fetch --clean site.yml" > antora.sh

      - name: Run Antora
        uses: docker://ghcr.io/asam-ev/project-guide-docker:4
        with:
          entrypoint: sh
          args: antora.sh

  
  deliverables:
    name: Create deliverables package
    runs-on: ubuntu-latest
    needs: [setup,antora]
    steps:
#       - name: Checkout interface
#         uses: actions/checkout@v3
#         with:
#           path: dist/open-simulation-interface

      - name: Checkout sensor model packaging
        uses: actions/checkout@v3
        with:
          repository: OpenSimulationInterface/osi-sensor-model-packaging
          path: dist/osi-sensor-model-packaging

      - name: Create README
        working-directory: dist
        run: |
          echo "/**********************************************************************************
          ***  ASAM OSI       		                                                ***
          ***  Version : ${{ needs.setup.outputs.VERSION }}       	                                        ***
          ***  Date:  $(cat DOCDATE)                                                       ***
          **********************************************************************************/

          the deliverables of ASAM OSI $VERSION include:

          - ASAM_OSI_Standard_${{ needs.setup.outputs.VERSION }}
          - open_simulation_interface_${{ needs.setup.outputs.VERSION }}
          - osi-sensor-model-packaging_${{ needs.setup.outputs.VERSION }}" > "README.txt"

      - name: Create deliverables package
        uses: actions/upload-artifact@v3
        with:
          name: deliverables
          path: dist



  publish:
    name: Add deliverables to release
    runs-on: ubuntu-latest
    needs: [deliverables]
    steps:
      - name: Add deliverables to release
        uses: irongut/EditRelease@v1.2.0
        with:
          id: ${{ github.event.release.id }}
          files: "deliverables.zip"
