name: GitHub Release Pipeline

on:
  release:
    types: [released]

jobs:
  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout interface
        uses: actions/checkout@v3
        with:
          path: dist/open-simulation-interface
      - name: Set vars
        id: vars
        working-directory: dist/open-simulation-interface
        run: |
          VERSION=$(git describe --tags --always |  sed 's/^v//') >> $GITHUB_OUTPUT 
          echo $VERSION
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}

  antora:
    name: Generate Antora content
    runs-on: ubuntu-22.04
    steps:          
      - name: Checkout Antora generator
        uses: actions/checkout@v3
        with:
          repository: OpenSimulationInterface/osi-antora-generator
          path: antora

      - name: Manipulate site.yml
        working-directory: antora
        run: |
          cat site.yml
          sed -i -E 's/doxygen: true//g' site.yml
          cat site.yml
#         sed -i -E 's/branches: (.*) \# (open-.*|osi-.*)//g' site.yml


      - name: Create run instructions
        run: echo "#!/bin/bash\n\ncd antora\nexec antora --stacktrace --fetch --clean site.yml" > antora.sh

      - name: Run Antora
        uses: docker://ghcr.io/asam-ev/project-guide-docker:4
        with:
          entrypoint: sh
          args: antora.sh
          
      - name: Test
        run: |
          cd antora
          ls
      
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with: 
          name: antora
          path: antora/site
  
  deliverables:
    name: Create deliverables package
    runs-on: ubuntu-latest
    needs: [setup,antora]
    steps:
      - name: Checkout interface
        uses: actions/checkout@v3
        with:
          path: dist/open-simulation-interface

      - name: Checkout sensor model packaging
        uses: actions/checkout@v3
        with:
          repository: OpenSimulationInterface/osi-sensor-model-packaging
          path: dist/osi-sensor-model-packaging
          
      - name: Retrieve Antora artifact
        uses: actions/download-artifact@v3
        with:
          name: antora

      - name: Create README
        working-directory: dist
        run: |
          echo ${{ needs.setup.outputs.VERSION }}
          echo "/**********************************************************************************
          ***  ASAM OSI       		                                                ***
          ***  Version : ${{ needs.setup.outputs.VERSION }}       	                                        ***
          ***  Date:  $(cat DOCDATE)                                                       ***
          **********************************************************************************/

          the deliverables of ASAM OSI $VERSION include:

          - ASAM_OSI_Standard_${{ needs.setup.outputs.VERSION }}
          - open_simulation_interface_${{ needs.setup.outputs.VERSION }}
          - osi-sensor-model-packaging_${{ needs.setup.outputs.VERSION }}" > "README.txt"
          cat README.txt

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with: 
          filename: ASAM_OSI_${{ needs.setup.outputs.VERSION }}.zip
          path: dist
          
      - name: test
        run: |
          ls
          cd dist
          ls
          
      - name: Create deliverables package
        uses: actions/upload-artifact@v3
        with:
          name: deliverables
          path: ASAM_OSI_${{ needs.setup.outputs.VERSION }}.zip

  publish:
    name: Add deliverables to release
    runs-on: ubuntu-latest
    needs: [deliverables, setup]
    steps:
      - name: Retrieve previous artifacts
        uses: actions/download-artifact@v3
        with:
          name: deliverables
        
      - name: Add deliverables to release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          files: "ASAM_OSI_${{ needs.setup.outputs.VERSION }}.zip"
